stock_terms = [
    "Beta (Stock Volatility)",
    "P/E Ratio (Price-to-Earnings)",
    "Dividend Yield",
    "Market Capitalization",
    "Short Selling",
    "Liquidity",
    "ETF (Exchange Traded Fund)",
    "Stock Split",
    "Stop-Loss Order",
    "Bull Market",
    "Bear Market",
    "Market Order",
    "Limit Order",
    "Day Trading",
    "Swing Trading",
    "Blue-Chip Stocks",
    "Growth Stocks",
    "Value Stocks",
    "Momentum Trading",
    "Technical Analysis",
    "Fundamental Analysis",
    "IPO (Initial Public Offering)",
    "Secondary Offering",
    "SPAC (Special Purpose Acquisition Company)",
    "Sector Rotation",
    "Market Index",
    "Dow Jones Industrial Average",
    "S&P 500",
    "Nasdaq Composite",
    "Russell 2000",
    "Volatility Index (VIX)",
    "Hedge Fund",
    "Mutual Fund",
    "Penny Stocks",
    "Market Maker",
    "Options Trading",
    "Call Option",
    "Put Option",
    "Strike Price",
    "Expiration Date",
    "Covered Call",
    "Naked Option",
    "Leverage",
    "Margin Trading",
    "Margin Call",
    "Trailing Stop Order",
    "Futures Contract",
    "Commodities Market",
    "Arbitrage",
    "Bond Yield",
    "Corporate Bonds",
    "Municipal Bonds",
    "Junk Bonds",
    "Stock Buyback",
    "Dividend Reinvestment Plan (DRIP)",
    "Stock Warrants",
    "Preferred Stock",
    "Common Stock",
    "Book Value",
    "Intrinsic Value",
    "52-Week High/Low",
    "Market Sentiment",
    "Earnings Report",
    "Quarterly Earnings",
    "Annual Report",
    "Balance Sheet",
    "Income Statement",
    "Cash Flow Statement",
    "Return on Equity (ROE)",
    "Return on Investment (ROI)",
    "Price-to-Book Ratio (P/B Ratio)",
    "PEG Ratio (Price/Earnings to Growth)",
    "Debt-to-Equity Ratio",
    "Capital Gains",
    "Capital Losses",
    "Dividends Per Share (DPS)",
    "Earnings Per Share (EPS)",
    "Share Buyback",
    "Over-the-Counter (OTC) Stocks",
    "Dark Pools",
    "Algorithmic Trading",
    "High-Frequency Trading (HFT)",
    "Candlestick Chart",
    "Head and Shoulders Pattern",
    "Double Bottom Pattern",
    "RSI (Relative Strength Index)",
    "MACD (Moving Average Convergence Divergence)",
    "Simple Moving Average (SMA)",
    "Exponential Moving Average (EMA)",
    "Support and Resistance Levels",
    "Fibonacci Retracement",
    "Elliott Wave Theory",
    "Dow Theory",
    "Breakout Trading",
    "Stop-Hunting",
    "Gap Trading",
    "Stock Dilution",
    "Sector ETFs",
    "Index Funds",
    "REIT (Real Estate Investment Trust)",
    "Commodities ETF",
    "T-Bills (Treasury Bills)",
    "Yield Curve",
    "Inflation Hedge",
    "Defensive Stocks",
    "Cyclical Stocks",
    "Forex (Foreign Exchange Market)",
    "Cryptocurrency Market",
    "SPY ETF (S&P 500 ETF)",
    "NSE (National Stock Exchange)",
    "BSE (Bombay Stock Exchange)",
    "Sensex (BSE Sensex)",
    "Nifty 50",
    "Nifty Bank",
    "SEBI (Securities and Exchange Board of India)",
    "RBI (Reserve Bank of India)",
    "SIP (Systematic Investment Plan)",
    "Mutual Funds Direct vs Regular Plans",
    "Equity Linked Savings Scheme (ELSS)",
    "Intraday Trading in India",
    "Commodity Trading on MCX (Multi Commodity Exchange)",
    "SME IPO (Small and Medium Enterprise IPO)",
    "Gilt Funds (Government Securities Mutual Funds)",
    "Dividend Distribution Tax (DDT)",
    "Securities Transaction Tax (STT)",
    "Aadhar-PAN Linking for Stock Investments",
    "Depository Participant (DP) in India",
    "Demat Account",
    "T+1 Settlement Cycle in India",
]
